### ISSUE TITLE
Achievements!

### ISSUE THREAD

**Issue by NonlinearFruit** [NonlinearFruit/Retrospector#30]
It would be pretty cool if there were achievements to strive for.

Some ideas:
- **Diversify:** Have 5+ categories
- **Social:** Have 3+ users
- **Trivial Pursuit:** Have 5+ factoids

- **Spree:** Review a media from each category (5+) in 1 day
- **Marathon:** Have 5+ user give reviews for 5+ media in 1 day

- **Friends:** Collect 10 reviews from a non-default user
- **Chums:** Collect 100 reviews from a non-default user
- **BFFs:** Collect 1,000 reviews from a non-default user

- **Popular:** Collect 100 reviews from non-default users
- **Famous:** Collect 1,000 reviews from non-default users
- **Anthropologist:** Collect 10,000 reviews from non-default users

- **Binge:** Consume 10 media in 1 category in 1 day
- **Loyalist:** Use Retrospector for 1 year
- **Star Gazer:** Star Retrospector on GitHub
- **Spectrum:** More categories than colors

- **Trvia Whiz:** Collect 100 factoids
- **Trivia Pro:** Collect 1,000 factoids
- **Trivia Expert:** Collect 10,000 factoids

- **Hobbyist:** Collect 100 media
- **Collector:** Collect 1,000 media
- **Connoisseur:** Collect 10,000 media

- **Jack of All Trades:** Have 10+ media in 5+ categories
- **Well Rounded:** Have 100+ media in 5+ categories
- **Renaissance Man:** Have 1,000+ media in 5+ categories

- **Weekend:** Consume 10 media each day for 3 consecutive days
- **Vacation:** Consume 10 media each day for 7 consecutive days
- **Unemployed :** Consume 10 media each day for 20 consecutive days

- **Hooked:** Review 1+ media per day for a month
- **Obsessed:** Review 1+ media per day for 90 days
- **Fanatic:** Review 1+ media per day for a year

**Comment by NonlinearFruit** [comment]
- **Favorite:** Review 1 media 5+ times
- **Classic:** Review 1 media 10+ times
- **Iconic:** Review 1 media 20+ times

**Comment by NonlinearFruit** [comment]
- **Wordy:** 1 long review
- **Thoughtful:** 10 long reviews
- **Scholarly:** 100 long reviews

**Comment by NonlinearFruit** [comment]
- **Dabbler:** Category with 100 media
- **Enthusiast:** Category with 1,000 media
- **Academic:** Category with 10,000 media

**Comment by NonlinearFruit** [comment]
- **Rock:** Media with Rock in the title
- **Paper:** Media with Paper in the title
- **Scissors:** Media with Scissors in the title
- **Lizard:** Media with Lizard in the title
- **Spock:** Media with Star Trek in the title

**Comment by JUG1T3R** [comment]
**- Inspector:** Opened the .config file
**- Paranoia:** Backed up your .script file
**- A True Masterpiece:** A title with 10+ episodes all rated a 10
**- Never Again:** Rated something as a 1
**- Inconsistency:** Have a title with both a 1 and a 10 rating
**- Apprentice:** Use Retrospector for 365 days
**- Journeyman:** Use Retrospector for 1825 days
**- Master:** Use Retrospector for 3650 days

**Comment by NonlinearFruit** [comment]
For reference, here is the icon set:
http://fontawesome.io/cheatsheet/

**Comment by NonlinearFruit** [comment]
New achievement ideas can be added to #36
