### ISSUE TITLE
Minor Suggestions

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#33]
It would be nice to have more options for "List the Top:" like adding a 25, 50, and 500 option buttons.

A key or a legend on the search tab explaining the 'and' 'or' and 'not' operators

Add a filter/operator to the search tab for showing media above (or below) a certain rating. Example: "movies >= 9"

**Comment by NonlinearFruit** [comment]
I implemented the List the Top bit, so I'm going to mark this as closed and create 2 new ones for the features I have done yet
