### ISSUE TITLE
More Achievements!

### ISSUE THREAD

**Issue by NonlinearFruit** [NonlinearFruit/Retrospector#36]
Here are the previous achievements that haven't been implemented:

 - **Inconsistency:** Have a title with both a 1 and a 10 rating
 - **A True Masterpiece:** A title with 10+ episodes all rated a 10
 - **Paranoia:** Backed up your .script file
 - **Spree:** Review a media from each category (5+) in 1 day
 - **Marathon:** Have 5+ user give reviews for 5+ media in 1 day
 - **Binge:** Consume 10 media in 1 category in 1 day

**Comment by JUG1T3R** [comment]
**- Nerd:** One media with 5 or more factoids on it
**- Behind the Curtain:** View Retrospector running in the terminal

**Comment by NonlinearFruit** [comment]
These are for Factoid types:

 - 100 factoids in a type
 - 1,000 factoids in a type
 - 10,000 factoids in a type
 - 100 factoids in each type (5+)
 - 1,000 factoids in each type (5+)
 - 10,000 factoids in each type (5+)

**Comment by NonlinearFruit** [comment]
An achievement for having a lot of reviews in a category and for the review distribution approximating a bell curve would be cool.

![image](https://cloud.githubusercontent.com/assets/6962125/25808075/f243b2a6-33d6-11e7-97d0-63229cfa33fe.png)
