### ISSUE TITLE
Save Button

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#37]
The save button doesn't activate when changes are made to media type (Series, Miniseries, Single)

**Comment by NonlinearFruit** [comment]
The save button will activate when you have edited the text in Title, Season, or Episode. Right now, media type does 'do' anything. If you had a series with a blank season and a blank episode, it would be counted as a single.

**Comment by JUG1T3R** [comment]
Gotcha. That makes sense.
