### ISSUE TITLE
Sticky Factoids

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#38]
When you hit the add an episode button it would be nice for all of the factoids to remain instead of having to re-enter them.

I think it would save time especially if you are collecting a lot of information that doesn't change that often (Comics: Writer, Penciller, Year, Story Arc)

**Comment by NonlinearFruit** [comment]
I like this idea a lot. Factoids should stick when you click `add episode` and `add season`. It would be easier to delete/edit changed information than to re-add it.
