### ISSUE TITLE
Ranking System

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#48]
It would be nice to have some way to rank your top 100 movies. For example I have 3 movies I've rated a 10, but I'd like to be able to distinguish between them which is my first, second, and third favorite.

Just having like a personal rank field while editing media that when entering a number will increment all other numbers greater than or equal to it by 1. Then also a new column in the List tab for personal rank or something. It would be especially nice cause I have about 12 movies rated as a 7 but there are clearly some I like more than others.

**Comment by NonlinearFruit** [comment]
## Current Solution
There are three ways 'around' this right now. 
 1. **Rewatch** it
    - The sorting is by average rating and then by number of reviews
 2. **Limit** the time frame
    - Use the current year or give a shorter custom range
 3. **Re-scale**
    - It could be that your favorite 7 should actually be an 8
    - or your least favorite 7 is should actually be a 6

## Future Solution
1. Should we try to re-enable decimal ratings? 
    - For example, `7.6` or `9.8`
    - Downside: If you watch 91 movies, you will still have at least 2 movies with the same rating

2. Should we create a tie-breaker field?
    - For example, `rank = 4`
    - Downside: If you watch a movie twice, it was the 4th 10 but now it is a 7. What happens to the rank?

**Comment by NonlinearFruit** [comment]
I'm going to close this. I don't know that there is any good solution besides re-reviewing. If we had decimal ratings, the problem would still crop-up.
