### ISSUE TITLE
Rock Paper Scissors Lizard Spock

### ISSUE THREAD

**Issue by NonlinearFruit** [NonlinearFruit/Retrospector#49]
I propose a modification in how these achievements are calculated:
 - **Rock:** Contains 'Rock' or 'Earth' in the title
- **Paper:** Contains 'Paper' or 'Book' in the title
- **Scissors:** Contains 'Scissor' or 'Blade' in the title
- **Lizard:** Contains 'Lizard' <s>or 'Jurassic'</s> or 'Godzilla' in the title
- **Spock:** Contains 'Star Trek' or 'Alien' in the title

Is this to easy? What could be a second option for 'Paper'?

**Comment by NonlinearFruit** [comment]
The second paper could be 'Origami'

**Comment by JUG1T3R** [comment]
The second paper could be 'Book'
