### ISSUE TITLE
Highscores

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#60]
This is something that I've just been keep track of mentally, but it would be interesting to know which month you consumed the most of each category of media. For example:

Movie: March 2017 (31)
Comic: July 2017 (180)
TV Series: _Month_, _Year_ ,(_Number of Media_) 

This way you have scores to beat and nerdy bragging rights.

**Comment by JUG1T3R** [comment]
There could also be a new batch of fresh achievements to go along with this too if you decide to implement it.

-Fanatic: Have a category with a highscore of over 100
-What are you Trying to Prove? : beat a highscore that was already over 100

**Comment by NonlinearFruit** [comment]
What do you think of these achievements?
- A category with High Score over 50
- A category with High Score over 100
- A category with High Score over 250

- Each category with High Scores over 10
- Each category with High Scores over 50
- Each category with High Scores over 100

**Comment by JUG1T3R** [comment]
I like the first set. The second set I don't think would be reasonably achievable by anyone with the category of Book or Movie.

**Comment by NonlinearFruit** [comment]
Is this more reasonable? I don't want it to be to simple for someone who has 'easy' categories

- Each category with High Scores over 10
- Each category with High Scores over 25
- Each category with High Scores over 50

**Comment by NonlinearFruit** [comment]
Should the high score list be generate with the achievements and displayed beneath them?

**Comment by JUG1T3R** [comment]
Yeah I think that'd be fine.
