### ISSUE TITLE
Auto-Fill Fields

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#62]
When typing in numbers for a media's Episode it tries to auto-fill unnecessarily. And adds an extra click to the data entry process in order to cancel the fill.

**Comment by NonlinearFruit** [comment]
What if recommendations are required to be 4+ characters? You are right that recommendations like `S44` or `E11` aren't useful.

**Comment by JUG1T3R** [comment]
Yeah I think recommendations that only appear after you've typed the first four characters would be more useful.
