### ISSUE TITLE
Scrape DB Plugins

### ISSUE THREAD

**Issue by onechrisjones** [NonlinearFruit/Retrospector#63]
Create a way to pull info from places like imdb. Then allow users to add their own implementations for special categories/media that they consume.

**Comment by NonlinearFruit** [comment]
I implemented this (or tried to) but it got pretty ugly so I pushed it to the `plugins` branch. I'm not sure how to do it logistically. Entering media this way takes away the benefit of the autocomplete (for finding duplicates) and it feels slower than just entering it manually. Maybe scraping should only pull in factoids and the description (and maybe episode name)?

![peek 2017-11-16 11-27](https://user-images.githubusercontent.com/6962125/32902766-48ad5f1c-cac1-11e7-8cd7-5ef06ee92fc0.gif)

**Comment by onechrisjones** [comment]
Dude... Friggin love this. When you already have a ton of structured data in there, it might be rough, but for a new user... this is amazing. I havent entered enough data to even use autocomplete yet... but i have some thoughts in infancy as to how that could work... 

STOKED!

**Comment by NonlinearFruit** [comment]
Here is the current solution:
 - Fill in the content your plugin needs
 - Click download icon
 - Double click the desired plugin
 - BOOM!

![peek 2017-12-02 22-08](https://user-images.githubusercontent.com/6962125/33521912-9ff5d1a2-d7ad-11e7-994d-12fca431b3d1.gif)
