### ISSUE TITLE
Media Highscore

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#65]
I think it would be useful to track which media from each category that you've consumed the most of. For example in my Comics category my highest ranking media would be Exiles (100) and in movies it would be Star Wars (8).

**Comment by JUG1T3R** [comment]
I think everything should be grouped based on category and then just by title. Creators(comic book writers, movie directors, television studios) are subject to change but they're still all working on the same subject material.

**Comment by NonlinearFruit** [comment]
For each category, all media with the same title are combined. The title with the largest media count wins that category or the title with the highest review count?

**Comment by NonlinearFruit** [comment]
I think counting the media would be better than counting the reviews. What if we do something like this and place it next to the highscores table?

### Top Media
| Category | Count | Title |
|--------------|-------|----------|
| Movie      | 8 | Avengers, The |
| TV Series| 80 | Avatar: The Last Airbender |
| Book | 80 | Sherlock Holmes |
