### ISSUE TITLE
Default User on Chart Tab

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#87]
I think if the chart tab only displayed the data for the default user instead of automatically having all users being checked it would be more useful for a default user who has a lot of reviews entered from a lot of people at one time. 

Here's what my monthly totals list for just movies looks like now with all users selected. Its just annoying cause it skews my chart so bad I have to change it every time I go onto that tab. 

![chart tab](https://user-images.githubusercontent.com/28473466/37602991-f355d07c-2b63-11e8-9ec9-0476783a052d.jpg)

**Comment by NonlinearFruit** [comment]
To do this we also need to add a "Select All" option. It currently defaults to everyone because you can double-click to select a single user and there is no way to check all.

**Comment by JUG1T3R** [comment]
I think adding a Select All would be a good substitute for this feature. Another change to that checklist could be making the default user appear at the top of the list instead of it just being alphabetical.

**Comment by NonlinearFruit** [comment]
Done. Default user is selected by default and is displayed at the top of the list (other users follow in alphabetical order). No 'Select All' button yet. Not sure what will look the best.
![image](https://user-images.githubusercontent.com/6962125/39371059-97032a26-4a0e-11e8-896b-2a7eb8b1612e.png)
