### ISSUE TITLE
Factoid charting bug (GIF Included)

### ISSUE THREAD

**Issue by CKalis** [NonlinearFruit/Retrospector#90]
In the Chart tab, the bottom section, [which you have already entertained the idea of removing](https://github.com/NonlinearFruit/Retrospector/issues/82), does not populate data correctly after changing selection via the drop-down menu directly to the left.

Here is the GIF of it in action, on the latest 1.2.4.1 pre-release, running Windows 10 x64 with Java 1.8.0_171.

![factoidbug](https://user-images.githubusercontent.com/5816420/39397951-2e2aed96-4ad5-11e8-87a8-8cc9883a5aa5.gif)

**Comment by NonlinearFruit** [comment]
This bug also happens to the Monthly Totals chart sometimes. It is a bug in JavaFX itself. We had a work around that fixed it, but it has cropped up again. Resizing the window, causes the labels to be redrawn which usually fixes it. But we do need a more permanent/friendly solution.
